### ISSUE TITLE
start.bat 闪退

### ISSUE THREAD

**Issue by choices7** [wangyuxiao2000/dds_parallel#1]
老哥 运行.bat文件闪退怎么解决

**Comment by wangyuxiao2000** [comment]
因为Linux和Windows对回车符的识别不同，请使用git clone指令拉取，不要直接download压缩包。

**Comment by choices7** [comment]
感谢老哥，git clone指令拉取就不闪退了。

![QQ_1732502498081](https://github.com/user-attachments/assets/baa0df54-4265-4033-8801-b36362eab030)
![QQ_1732502682681](https://github.com/user-attachments/assets/01d9658d-b4d1-426a-be7e-e0e0a1cf8592)
**“source/MATLAB”文件夹中找不到“main.m”文件**

**Comment by wangyuxiao2000** [comment]
不好意思，文档还没更新，是另一个项目的文档贴过来了；有使用上的问题可以加我qq，1969018481.
